### ISSUE TITLE
Wrong layout with Chinese characters

### ISSUE THREAD

**Issue by labkode** [ryanuber/columnize#9]
This is the diplay:

```
PATHSPEC                     TYPE  SIZE  MIMETYPE  CHECKSUM
dirs                         0     816
myblob                       1     5937
mynewfile                    1     5937
New document.txt             1     5937
New\' file wrong weird name  1     5937
豆贝尔维                         1     5937
```

Can be a problem of not using rune functions ?

**Comment by ryanuber** [comment]
@labkode I think this issue actually extends pretty far beyond rune functions. The double wide characters are a bit difficult to deal with, because essentially to support this nicely we would need some function which was able to detect the actual cell width of each character of text. I looked into this a little, and determining cell width seems largely unstandardized today and is probably more than this library will be responsible for. The closest I found was golang.org/x/text/width (see the enormous mapping table [here](https://github.com/golang/text/blob/master/width/tables.go#L195)). The main issue is that you end up having to iterate over every single character of text to check its individual width by looking it up in the table, so likely this will result in hundreds or thousands of function calls which will severely degrade the performance of the library.

I'm going to close this for now but if in the future we have an easy way of getting the true cell width of a string easily (similar to a call to `len()`), then we can definitely revisit this. Thanks for reporting the issue anyways!
